kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: projectriff
  labels:
    projectriff.io/release: devel
    # Add these permissions to the "admin" and "edit" default roles.
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["build.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["request.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["stream.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: projectriff-readonly
  labels:
    projectriff.io/release: devel
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups: ["build.projectriff.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["request.projectriff.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["stream.projectriff.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: projectriff-admin
  labels:
    projectriff.io/release: devel
rules:
  - apiGroups: ["build.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["request.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["stream.projectriff.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "serviceaccounts", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/finalizers"] # finalizers are needed for the owner reference of the webhook
    verbs: ["*"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["build.knative.dev"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations"]
    verbs: ["*"]
